export interface BlogPost {
    slug: string;
    title: string;
    description: string;
    date: string;
    readTime: string;
    category: string;
    image?: string;
}

export const blogPosts: BlogPost[] = [
    {
        slug: "state-code-38-gst-ladakh",
        title: "State Code 38 in GST – Meaning, Usage, and Examples",
        description: "Learn about GST State Code 38 for Ladakh. Understand how to use state code 38 in GST invoices, GSTIN format, and avoid common errors.",
        date: "February 3, 2025",
        readTime: "5 min read",
        category: "GST Guide",
        image: "/blog-state-code-38.png",
    },
    {
        slug: "best-free-online-financial-calculators-2026",
        title: "Best Free Online Financial Calculators for 2026",
        description: "Discover the top financial tools you need in 2026. From GST and EMI to Compound Interest, stay ahead of your finances with our suite of free professional calculators.",
        date: "January 18, 2026",
        readTime: "9 min read",
        category: "Tools",
        image: "/blog-best-calculators-2026.png",
    },
    {
        slug: "how-percentage-works-shopping-salary",
        title: "How Percentage Works in Shopping, Salary & Business",
        description: "Master percentage calculations used in daily life. Learn how to calculate discounts, salary hikes, taxes, and profit margins with real-world examples.",
        date: "January 18, 2026",
        readTime: "8 min read",
        category: "Finance",
        image: "/blog-percentage-shopping-salary.png",
    },
    {
        slug: "how-compound-interest-works",
        title: "How Compound Interest Works — The Easiest Guide with Examples",
        description: "Learn how compound interest creates exponential wealth. Understand the Rule of 72, compounding frequency, and real-life examples for retirement and education funds.",
        date: "January 18, 2026",
        readTime: "11 min read",
        category: "Finance",
        image: "/blog-compound-interest-works.png",
    },
    {
        slug: "simple-vs-compound-interest",
        title: "Simple vs Compound Interest — Which Is Better for You?",
        description: "Discover the key differences between simple and compound interest. Learn which one benefits you more for loans, investments, and long-term savings in 2026.",
        date: "January 18, 2026",
        readTime: "9 min read",
        category: "Finance",
        image: "/blog-simple-vs-compound.png",
    },
    {
        slug: "what-is-emi-calculator",
        title: "What Is EMI? How Banks Calculate It (Formula, Examples & Mistakes)",
        description: "Complete guide to understanding EMI calculations with real examples, formula breakdown, and common mistakes to avoid when taking home loans, car loans, and personal loans.",
        date: "January 18, 2026",
        readTime: "7 min read",
        category: "Finance",
        image: "/blog-emi-strategy.png",
    },
    {
        slug: "mastering-gst-calculator",
        title: "Mastering the GST Calculator: A Comprehensive Guide for Businesses in 2026",
        description: "A technical and practical guide to understanding GST calculations, formulas, and compliance for developers and finance professionals in 2026.",
        date: "January 8, 2026",
        readTime: "8 min read",
        category: "Finance",
        image: "/blog-mastering-gst.png",
    },
    {
        slug: "gst-state-codes-list-2025",
        title: "GST State Codes List 2025: Complete Guide for E-way Bills",
        description: "Complete list of GST State Codes in India (01-37). Essential for GST registration, e-way bills, and filing returns.",
        date: "January 30, 2025",
        readTime: "3 min read",
        category: "Reference",
        image: "/blog-gst-state-codes.png",
    },
    {
        slug: "how-to-calculate-gst-backwards",
        title: "How to Calculate GST Backwards (Reverse GST) – Step-by-Step Guide",
        description: "Master reverse GST calculation with step-by-step examples for 5%, 12%, 18%, and 28% rates. Learn the formula to extract base price from MRP.",
        date: "February 3, 2025",
        readTime: "8 min read",
        category: "GST Guide",
        image: "/blog-reverse-gst.png",
    },
    {
        slug: "composition-scheme-vs-regular-gst",
        title: "Composition Scheme vs Regular GST: Which is Better?",
        description: "Compare Composition Scheme vs Regular GST scheme. Understand the pros and cons, tax rates, and compliance burden.",
        date: "January 25, 2025",
        readTime: "7 min read",
        category: "Business Guide",
        image: "/blog-composition-vs-regular.png",
    },
    {
        slug: "gst-invoice-format-for-freelancers",
        title: "GST Invoice Format for Freelancers: The Ultimate Guide",
        description: "Learn how to create a compliant GST invoice. Download free Excel templates and understand mandatory fields.",
        date: "January 22, 2025",
        readTime: "6 min read",
        category: "Freelancing",
        image: "/blog-gst-invoice.png",
    },
    {
        slug: "gst-on-electronics-mobile-laptops-2025",
        title: "GST on Electronics 2025: Mobile Phones & Laptops",
        description: "Complete guide to GST rates on electronics in India for 2025. Know the tax rates for mobile phones, laptops, and accessories.",
        date: "January 20, 2025",
        readTime: "5 min read",
        category: "Consumer Electronics",
        image: "/blog-gst-electronics.png",
    },
    {
        slug: "gst-calculation-for-freelancers-india",
        title: "GST Calculation for Freelancers in India: Complete Guide 2025",
        description: "Everything freelancers need to know about GST registration, calculation, and filing. Learn how to calculate GST on your freelance income and stay compliant.",
        date: "January 15, 2025",
        readTime: "8 min read",
        category: "Freelancers",
        image: "/blog-freelancer-gst.png",
    },
    {
        slug: "gst-rate-chart-2025-india",
        title: "GST Rate Chart India 2025: Complete List with Examples",
        description: "Comprehensive GST rates chart for 2025. Find GST rates for all goods and services including HSN codes, examples, and recent updates.",
        date: "January 10, 2025",
        readTime: "6 min read",
        category: "GST Rates",
        image: "/blog-gst-rates-2025.png",
    },
    {
        slug: "gst-calculator-excel-download",
        title: "GST Calculator Excel Download: Free Template & Guide",
        description: "Download free GST calculation Excel templates. Learn how to create your own GST calculator in Excel with formulas and examples.",
        date: "January 8, 2025",
        readTime: "5 min read",
        category: "Tools & Resources",
        image: "/blog-excel-calculator.png",
    },
    {
        slug: "difference-between-gst-and-vat",
        title: "Difference Between GST and VAT: Key Changes Explained",
        description: "Understand the differences between GST and VAT systems in India. Learn how GST replaced VAT and what it means for businesses.",
        date: "January 5, 2025",
        readTime: "7 min read",
        category: "GST Basics",
        image: "/blog-difference-gst-vat.png",
    },
];
