import jsPDF from 'jspdf';

interface CalculationData {
    type: 'add' | 'reverse';
    amount: number;
    gstRate: number;
    gstAmount: number;
    totalAmount: number;
}

export const generateCalculationPDF = (data: CalculationData): void => {
    const doc = new jsPDF();

    // Set colors
    const primaryColor: [number, number, number] = [79, 70, 229]; // Indigo
    const textColor: [number, number, number] = [31, 41, 55]; // Gray-800

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('GST Calculation Report', 105, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Easy GST Calculator', 105, 30, { align: 'center' });

    // Reset text color
    doc.setTextColor(...textColor);

    // Date and Type
    const currentDate = new Date().toLocaleDateString('en-IN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });

    doc.setFontSize(10);
    doc.text(`Date: ${currentDate}`, 20, 55);
    doc.text(`Calculation Type: ${data.type === 'add' ? 'Add GST' : 'Reverse GST'}`, 20, 62);

    // Calculation Details Box
    doc.setDrawColor(229, 231, 235); // Gray-200
    doc.setLineWidth(0.5);
    doc.rect(20, 75, 170, 80);

    // Title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Calculation Details', 25, 85);

    // Details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');

    let yPos = 100;
    const lineHeight = 12;

    if (data.type === 'add') {
        doc.text(`Original Amount:`, 25, yPos);
        doc.text(`₹${data.amount.toFixed(2)}`, 150, yPos, { align: 'right' });

        yPos += lineHeight;
        doc.text(`GST Rate:`, 25, yPos);
        doc.text(`${data.gstRate}%`, 150, yPos, { align: 'right' });

        yPos += lineHeight;
        doc.setFont('helvetica', 'bold');
        doc.text(`GST Amount:`, 25, yPos);
        doc.text(`₹${data.gstAmount.toFixed(2)}`, 150, yPos, { align: 'right' });

        // Separator
        yPos += lineHeight;
        doc.setDrawColor(229, 231, 235);
        doc.line(25, yPos - 5, 185, yPos - 5);

        yPos += 5;
        doc.setFontSize(14);
        doc.setTextColor(...primaryColor);
        doc.text(`Total Amount:`, 25, yPos);
        doc.text(`₹${data.totalAmount.toFixed(2)}`, 150, yPos, { align: 'right' });
    } else {
        doc.text(`Total Amount (Inclusive):`, 25, yPos);
        doc.text(`₹${data.amount.toFixed(2)}`, 150, yPos, { align: 'right' });

        yPos += lineHeight;
        doc.text(`GST Rate:`, 25, yPos);
        doc.text(`${data.gstRate}%`, 150, yPos, { align: 'right' });

        yPos += lineHeight;
        doc.setFont('helvetica', 'bold');
        doc.text(`GST Amount:`, 25, yPos);
        doc.text(`₹${data.gstAmount.toFixed(2)}`, 150, yPos, { align: 'right' });

        // Separator
        yPos += lineHeight;
        doc.setDrawColor(229, 231, 235);
        doc.line(25, yPos - 5, 185, yPos - 5);

        yPos += 5;
        doc.setFontSize(14);
        doc.setTextColor(...primaryColor);
        doc.text(`Original Amount:`, 25, yPos);
        doc.text(`₹${data.totalAmount.toFixed(2)}`, 150, yPos, { align: 'right' });
    }

    // Footer
    doc.setTextColor(107, 114, 128); // Gray-500
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Easy GST Calculator', 105, 270, { align: 'center' });
    doc.text('https://easy-gst-calculator.netlify.app', 105, 277, { align: 'center' });

    // Disclaimer
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const disclaimer = 'This is a computer-generated document. Please verify the calculations for accuracy.';
    doc.text(disclaimer, 105, 285, { align: 'center', maxWidth: 170 });

    // Save PDF
    const fileName = `GST_Calculation_${Date.now()}.pdf`;
    doc.save(fileName);
};
