'use client';

import { Button } from '@/components/ui/button';

interface PrintInvoiceButtonProps {
  amount: number;
  taxAmount: number;
  totalAmount: number;
  rate: number;
  taxType: string;
  currencySymbol: string;
  formatCurrency: (value: number, currency?: 'INR' | 'USD') => string;
  currency: 'INR' | 'USD';
}

export default function PrintInvoiceButton({
  amount,
  taxAmount,
  totalAmount,
  rate,
  taxType,
  currencySymbol,
  formatCurrency,
  currency,
}: PrintInvoiceButtonProps) {
  const handlePrint = () => {
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) return;

    const invoiceHTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>GST Calculation Invoice</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              max-width: 600px;
              margin: 0 auto;
            }
            .header {
              text-align: center;
              border-bottom: 3px solid #6366f1;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #6366f1;
              margin: 0;
            }
            .details {
              margin-bottom: 30px;
            }
            .detail-row {
              display: flex;
              justify-content: space-between;
              padding: 10px 0;
              border-bottom: 1px solid #e5e7eb;
            }
            .detail-row:last-child {
              border-bottom: 2px solid #6366f1;
              font-weight: bold;
              font-size: 1.2em;
              margin-top: 10px;
            }
            .footer {
              text-align: center;
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              color: #6b7280;
              font-size: 0.9em;
            }
            @media print {
              body { padding: 20px; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>GST Calculation Invoice</h1>
            <p>GST Calculator India</p>
          </div>
          <div class="details">
            <div class="detail-row">
              <span>Amount (excluding tax):</span>
              <span>${currencySymbol}${formatCurrency(amount, currency)}</span>
            </div>
            <div class="detail-row">
              <span>Tax Type:</span>
              <span>${taxType === 'GST' ? `GST ${rate}%` : taxType === 'IGST' ? `IGST ${rate}%` : `CGST ${rate/2}% + SGST ${rate/2}%`}</span>
            </div>
            <div class="detail-row">
              <span>Tax Amount:</span>
              <span>${currencySymbol}${formatCurrency(taxAmount, currency)}</span>
            </div>
            <div class="detail-row">
              <span><strong>Total (including tax):</strong></span>
              <span><strong>${currencySymbol}${formatCurrency(totalAmount, currency)}</strong></span>
            </div>
          </div>
          <div class="footer">
            <p>Generated by GST Calculator India</p>
            <p>easy-gst-calculator.netlify.app</p>
            <p>Date: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(invoiceHTML);
    printWindow.document.close();
    
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  return (
    <Button
      onClick={handlePrint}
      variant="outline"
      size="sm"
      className="transition-all hover:scale-105"
      aria-label="Print invoice"
    >
      <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
      </svg>
      Print Invoice
    </Button>
  );
}

